env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: [ ]
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  indent: [ "error", 4 ],
  react/jsx-indent: [ "error", 4 ],
  react/jsx-indent-props: [ "error", 4 ],
  react/jsx-filename-extension: [ 1, { extensions: [ ".js", ".jsx" ] } ],
  react/jsx-curly-brace-presence: [ 1, { props: "always", children: "always" } ],
  react-function-component-definition: [ off, { namedComponents: "arrow-function" } ],
  react/jsx-no-useless-fragment: [ off ],
  react/jsx-props-no-spreading: [ off ],
  no-param-reassign: ["warn"],
  quotes: [ "error", "double" ],
  no-unused-vars: warn,
  global-require: warn,
  no-console: warn,
  no-shadow: off,

}
